name: CI


on:
  pull_request:
  push:
    branches:
      - '*'
  schedule:
    # daily (`@daily` not supported, see
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events )
    #
    # Runs on default/base branch (see
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule )
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # see https://github.com/goanpeca/setup-miniconda/#important
        shell: bash -l {0}

    steps:
      # CI setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conda Bootstrap
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          channel-priority: strict
          channels: conda-forge
          python-version: 3.9
      - name: Conda Config
        run: |
          conda config --set always_yes yes
          conda config --set changeps1 no
          conda config --set pip_interop_enabled True

      # Installation into the `test` environment

#      - name: Conda Install conda-requirements.txt
#        # run this AFTER pyarrow, since this is less restrictive (so conda doesn't spend too much time downgrading)
#        run: conda install --file=conda-requirements.txt
      - name: Pip Install
        run: pip install .

      - name: Run test
        run: pytest test_bot.py

      - name: Run model
        if: github.ref != 'refs/heads/master'
        run: python bot.py
        env:
          LEADERBOARD_API_USERNAME: ${{ secrets.LEADERBOARD_API_USERNAME }}
          LEADERBOARD_API_PASSWORD: ${{ secrets.LEADERBOARD_API_PASSWORD }}
